### PR TITLE
Added non-continuous gradients from colorbrewer

### PR DESCRIPTION
**Pull request by ValentinKaisermayer**
At least for line plots this seems better than https://github.com/JuliaPlots/PlotUtils.jl/pull/67

### CODE REVIEW

**Comment by daschw** [comment]
Thanks!
I think 
```julia
for sym in (:Set1, :Set2, ...)
    _themes[sym] = PlotTheme(
        palette = expand_palette(colorant"white", cgrad(sym).colors; lchoices = [57], cchoices = [100]),
    )
end
```
should also work as a shorter implementation.
It uses `cgrad` from PlotUtils

**Comment by daschw** [comment]
... but requires a new release from PlotUtils.

**Comment by mkborregaard** [comment]
I don't think this is the right place to add the palettes - we should fix this in PlotUtils

**Comment by daschw** [comment]
Right, then one could just do `theme(palette = :grad)` or `default(palette = :grad)` for any :grad defined in PlotUtils.

**Comment by BeastyBlacksmith** [comment]
I think this is also resolved by the ColorSchemes integration

**Pull request closed without merging**
