### PR TITLE
get Juno theme colors from Atom syntax theme

### LINKED ISSUE #25: Update juno syntax theme
The `:juno` syntax theme can now be specified using `Juno.syntaxcolors()` to use the exact colors chosen for the current juno session. This could be implemented without a Juno dep using Requires.jl. https://github.com/JunoLab/Juno.jl/issues/15#issuecomment-357696719

### LINKED ISSUE #5622: Update juno syntax theme
The `:juno` syntax theme can now be specified using `Juno.syntaxcolors()` to use the exact colors chosen for the current juno session. This could be implemented without a Juno dep using Requires.jl. https://github.com/JunoLab/Juno.jl/issues/15#issuecomment-357696719

### PR DESCRIPTION
**Pull request by pfitzseb**
plotthemes jl

Fixes JuliaPlots/Plots.jl#5622.

### CODE REVIEW

**Comment by mkborregaard** [comment]
With your branch I get
```julia
julia> using Plots
WARNING: Error requiring Juno from PlotThemes:
Unknown color: #0
Stacktrace:
 [1] _parse_colorant(::String) at /Users/michael/.julia/v0.6/Colors/src/parse.jl:104
 [2] (::PlotThemes.##28#31)(::Pair{String,UInt32}) at ./<missing>:0
 [3] all(::Base.##179#181, ::Base.Generator{Dict{String,UInt32},PlotThemes.##28#31}) at ./reduce.jl:598
 [4] Dict(::Base.Generator{Dict{String,UInt32},PlotThemes.##28#31}) at ./dict.jl:147
 [5] err(::PlotThemes.##15#22, ::Module, ::String) at /Users/michael/.julia/v0.6/Requires/src/require.jl:42
 [6] withpath(::PlotThemes.##14#21, ::String) at /Users/michael/.julia/v0.6/Requires/src/require.jl:32
 [7] listenmod(::PlotThemes.##13#20, ::Symbol) at /Users/michael/.julia/v0.6/Requires/src/require.jl:13
 [8] macro expansion at /Users/michael/.julia/v0.6/Requires/src/require.jl:52 [inlined]
 [9] (::PlotThemes.##12#19)() at /Users/michael/.julia/v0.6/Requires/src/init.jl:17
 [10] __init__() at /Users/michael/.julia/v0.6/Requires/src/init.jl:24
 [11] _include_from_serialized(::String) at ./loading.jl:157
 [12] _require_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:200
 [13] _require_search_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:236
 [14] _require(::Symbol) at ./loading.jl:441
 [15] require(::Symbol) at ./loading.jl:405
 [16] _include_from_serialized(::String) at ./loading.jl:157
 [17] _require_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:200
 [18] _require(::Symbol) at ./loading.jl:464
 [19] require(::Symbol) at ./loading.jl:405
 [20] macro expansion at /Users/michael/.juliarc.jl:25 [inlined]
 [21] (::##3#4)() at ./event.jl:73
```

**Comment by mkborregaard** [comment]
I think there's an issue with my syntax theme - so not due to this PR.

**Comment by pfitzseb** [comment]
grafik
This also automatically generates a gradient with colors that are sufficiently saturated. Seems to look okayish for a couple of themes I tried.

**Comment by daschw** [comment]
That looks great @pfitzseb!
However, with the [Atom Material UI](https://atom.io/themes/atom-material-ui) it does not work for me: 
When I try to acces the syntaxcolors from within Atom, I get this:
```julia
julia> Juno.syntaxcolors()
WARNING: Atom.jl: unrecognised message cancelCallback.
```
and Julia hangs.

**Comment by pfitzseb** [comment]
Fixed with https://github.com/JunoLab/atom-julia-client/commit/3d82170b201e6ff1b7d151eca6f28b9cd46d7eb4.

**Comment by daschw** [comment]
Great! I guess we should wait for a new Juno/Atom release before merging this, right?

**Comment by pfitzseb** [comment]
Yeah.

**Comment by pfitzseb** [comment]
New Juno version is out, so this should be fixed now.

**Comment by mkborregaard** [comment]
Wonderful. I'd like to do something with the generated gradient - but perhaps we could just merge and I could make a separate PR?

**Comment by pfitzseb** [comment]
Yeah, the code that generates the gradient right now is about as dumb as can be -- would be cool to have something more fancy for that :)

**Comment by mkborregaard** [comment]
I think we'd get the best results by picking one of the predefined gradients based on its similarity to the syntax colors, using `Colors.colordiff`.

**Comment by pfitzseb** [comment]
How boring :D But yes, you're probably right.

**Comment by mkborregaard** [comment]
I'm old enough to prefer the pragmatic solution :-D

**Pull request merged**
