### PR TITLE
Add gruvbox dark and light themes

### PR DESCRIPTION
**Pull request by zacharyneveu**
Just added my favorite theme.

### CODE REVIEW

**Comment by mkborregaard** [comment]
nice but do you also have a plot example (`showtheme`) to add to the readme?

**Comment by zacharyneveu** [comment]
Happy to include those, any tips on how to host them the way the others are hosted?

**Comment by daschw** [comment]
We used https://github.com/JuliaPlots/Plots.jl/issues/5631 to drag and drop images, then copy their link adresses and paste them into the readme.

**Comment by daschw** [comment]
@zacharyneveu Could you update this PR to adopt to the changes in https://github.com/JuliaPlots/PlotThemes.jl/pull/36, i.e. replace the `gradient` keys with `colorgradient` in lines 56 and 67 of src/gruvbox.jl?

**Comment by daschw** [comment]
I'll add the changes and the plot example in a separate PR.

**Pull request merged**
