### PR TITLE
update showtheme images in README

### PR DESCRIPTION
**Pull request by daschw**

### CODE REVIEW

**Comment by daschw** [comment]
Now, I'm not sure any more if I should really add the images to the repo. On the one hand, it would be easier to update and add new images. On the other hand, this probably increases the package size.

**Comment by mkborregaard** [comment]
Could we generate and take them from PlotReferenceImages?

**Comment by daschw** [comment]
Yes, but I'm not sure if it's really easier for a contributor to upload them to PlotReferenceImages than to just paste them in a issue here and copy the link, as we do now.

**Comment by daschw** [comment]
I'll use our old approach for now.

**Pull request closed without merging**
