### PR TITLE
seaborn palettes added

### PR DESCRIPTION
**Pull request by isentropic**
Relevant to discussion in https://github.com/JuliaPlots/Plots.jl/issues/2510

I did not add screenshots yet, but will do if needed (some screenshots can be seen in https://github.com/JuliaPlots/Plots.jl/issues/2510)

### CODE REVIEW

**Comment by mkborregaard** [comment]
Great. 
Should we add the color palettes to PlotUtils instead and just use them here? 
And yes, screenshots in the readme for discovery would be good

**Comment by isentropic** [comment]
Where should I upload the screenshots?
The images in the readme.md file are pointing to some https://raw.githubusercontent.com/ like link, perhaps screenshots were put in some issue, or may I create a directory with screenshots?

**Comment by mkborregaard** [comment]
Yes, a classic trick is to upload them in an issue comment - you don't even need to submit the comment to get the url

**Comment by isentropic** [comment]
@mkborregaard I added the screenshots and the default color gradient seaborn uses. 
The gradient colorscheme is subtly different from default `fire`, it is called `rocket` but it looks much better to me. 
Justification on why these colors look better is found in the first paragraph [here ](https://seaborn.pydata.org/tutorial/color_palettes.html)
Personally, I would want to put `seaborn_deep` (default) theme higher on the theme order, as it is widely used in python community and has some fame already.
Additionally, just wanted you to know that screenshots are missing `pi`, I could not get around it as much as I tried with GR backend. It works with PyPlot but the plots themselves look somewhat different then.

**Comment by isentropic** [comment]
@mkborregaard I'm having trouble passing "Pull Request Labeler" at this point I'm not sure if it is on my end

**Comment by asinghvi17** [comment]
Don't worry about the labeler - that looks like something on our end.

**Comment by daschw** [comment]
With https://github.com/JuliaPlots/PlotUtils.jl/pull/87 we will be able to use all palettes from https://github.com/JuliaGraphics/ColorSchemes.jl. So I suggest submitting a PR to ColorSchemes with  the seaborn palettes instead.

**Comment by BeastyBlacksmith** [comment]
Seaborn is now available via ColorSchemes

**Pull request closed without merging**
